# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24784f77b8a09f5128dcfe7465f93bffc83a9664d4b3d86ee3cb36cde42429f38fa757063054150a882fa230858554b680bdeff580c81f85f8529600a7738325

test:
  secret_key_base: d14eec894f4b3dc0af95169b79f6a829e77de360ad960bdaa53a20f775c143c3c959027ee14ac7357100803fd28caafcba886a7497c3ab8f6c19099e709cd0d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
