# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586b816477a174723c4780337642ff415457f86e8733c8f7d48c16ab8392e7743c24e241016b5b593569deee911e771d5f896d2a4e51f0b0a2c715044640f9c2

test:
  secret_key_base: 4786e4ced8a81987f7b00806d88920f7639414716f2555c2fc58374fb784d1803329c972c49ca19d01e6081feac66d08f57446faea28c994ed40902528817a7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
