# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61ba2740e25e7a0ab88db15cf5f4251646b527b8ee04709939a67d2619258918924851eba268469d55e61548516c19abe8c4d2ecb467ed7d451ea76dc00329ec

test:
  secret_key_base: 02ff6286eecb314a3b23695da9b953340815834f3ca1abbe0b235a948fcf750fe6dda15e56f551a29883fa5c850dfeac14d2947870a8d71d5c7597a1c5e05557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
